/******************************************************************************
 *
 * Module: Gpt
 *
 * File Name: Gpt_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Eslam - Taha - Sara
 ******************************************************************************/

#include "Gpt.h"
/*
 * Module Version 1.0.0
 */

#define GPT_PBCFG_SW_MAJOR_VERSION              (1U)
#define GPT_PBCFG_SW_MINOR_VERSION              (0U)
#define GPT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define GPT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define GPT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define GPT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Gpt_PBcfg.c and Gpt.h files */


/* Software Version checking between Gpt_PBcfg.c and Gpt.h files */

/*
 * PB structure used with Gpt_Init API
 */

const Gpt_ConfigType Gpt_Configuration = {
		GPT_0_ChannelStatus_CONFIG, GPT_0_ChannelState_CONFIG, GPT_0_CHANNEL_TYPE_CONFIG, GPT_0_VALUE_TYPE_CONFIG, GPT_0_MODE_TYPE_CONFIG, GPT_0_TARGET_NUM_TICKS_CONFIG, GPT_0_COUNTER_REPETITION_TYPE_CONFIG,  GPT_0_CLOCK_PRESCALER_CONFIG, GPT_0_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_0_CHANNEL_COUNTING_MODE_CONFIG, GPT_0_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_1_ChannelStatus_CONFIG,GPT_1_ChannelState_CONFIG, GPT_1_CHANNEL_TYPE_CONFIG, GPT_1_VALUE_TYPE_CONFIG, GPT_1_MODE_TYPE_CONFIG, GPT_1_TARGET_NUM_TICKS_CONFIG, GPT_1_COUNTER_REPETITION_TYPE_CONFIG,  GPT_1_CLOCK_PRESCALER_CONFIG, GPT_1_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_1_CHANNEL_COUNTING_MODE_CONFIG, GPT_1_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_2_ChannelStatus_CONFIG,GPT_2_ChannelState_CONFIG, GPT_2_CHANNEL_TYPE_CONFIG, GPT_2_VALUE_TYPE_CONFIG, GPT_2_MODE_TYPE_CONFIG, GPT_2_TARGET_NUM_TICKS_CONFIG, GPT_2_COUNTER_REPETITION_TYPE_CONFIG,  GPT_2_CLOCK_PRESCALER_CONFIG, GPT_2_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_2_CHANNEL_COUNTING_MODE_CONFIG, GPT_2_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_3_ChannelStatus_CONFIG,GPT_3_ChannelState_CONFIG, GPT_3_CHANNEL_TYPE_CONFIG, GPT_3_VALUE_TYPE_CONFIG, GPT_3_MODE_TYPE_CONFIG, GPT_3_TARGET_NUM_TICKS_CONFIG, GPT_3_COUNTER_REPETITION_TYPE_CONFIG,  GPT_3_CLOCK_PRESCALER_CONFIG, GPT_3_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_3_CHANNEL_COUNTING_MODE_CONFIG, GPT_3_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_4_ChannelStatus_CONFIG,GPT_4_ChannelState_CONFIG, GPT_4_CHANNEL_TYPE_CONFIG, GPT_4_VALUE_TYPE_CONFIG, GPT_4_MODE_TYPE_CONFIG, GPT_4_TARGET_NUM_TICKS_CONFIG, GPT_4_COUNTER_REPETITION_TYPE_CONFIG,  GPT_4_CLOCK_PRESCALER_CONFIG, GPT_4_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_4_CHANNEL_COUNTING_MODE_CONFIG, GPT_4_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_5_ChannelStatus_CONFIG,GPT_5_ChannelState_CONFIG, GPT_5_CHANNEL_TYPE_CONFIG, GPT_5_VALUE_TYPE_CONFIG, GPT_5_MODE_TYPE_CONFIG, GPT_5_TARGET_NUM_TICKS_CONFIG, GPT_5_COUNTER_REPETITION_TYPE_CONFIG,  GPT_5_CLOCK_PRESCALER_CONFIG, GPT_5_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_5_CHANNEL_COUNTING_MODE_CONFIG, GPT_5_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_6_ChannelStatus_CONFIG,GPT_6_ChannelState_CONFIG, GPT_6_CHANNEL_TYPE_CONFIG, GPT_6_VALUE_TYPE_CONFIG, GPT_6_MODE_TYPE_CONFIG, GPT_6_TARGET_NUM_TICKS_CONFIG, GPT_6_COUNTER_REPETITION_TYPE_CONFIG,  GPT_6_CLOCK_PRESCALER_CONFIG, GPT_6_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_6_CHANNEL_COUNTING_MODE_CONFIG, GPT_6_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_7_ChannelStatus_CONFIG,GPT_7_ChannelState_CONFIG, GPT_7_CHANNEL_TYPE_CONFIG, GPT_7_VALUE_TYPE_CONFIG, GPT_7_MODE_TYPE_CONFIG, GPT_7_TARGET_NUM_TICKS_CONFIG, GPT_7_COUNTER_REPETITION_TYPE_CONFIG,  GPT_7_CLOCK_PRESCALER_CONFIG, GPT_7_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_7_CHANNEL_COUNTING_MODE_CONFIG, GPT_7_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_8_ChannelStatus_CONFIG,GPT_8_ChannelState_CONFIG, GPT_8_CHANNEL_TYPE_CONFIG, GPT_8_VALUE_TYPE_CONFIG, GPT_8_MODE_TYPE_CONFIG, GPT_8_TARGET_NUM_TICKS_CONFIG, GPT_8_COUNTER_REPETITION_TYPE_CONFIG,  GPT_8_CLOCK_PRESCALER_CONFIG, GPT_8_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_8_CHANNEL_COUNTING_MODE_CONFIG, GPT_8_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_9_ChannelStatus_CONFIG,GPT_9_ChannelState_CONFIG, GPT_9_CHANNEL_TYPE_CONFIG, GPT_9_VALUE_TYPE_CONFIG, GPT_9_MODE_TYPE_CONFIG, GPT_9_TARGET_NUM_TICKS_CONFIG, GPT_9_COUNTER_REPETITION_TYPE_CONFIG,  GPT_9_CLOCK_PRESCALER_CONFIG, GPT_9_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_9_CHANNEL_COUNTING_MODE_CONFIG, GPT_9_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_10_ChannelStatus_CONFIG,GPT_10_ChannelState_CONFIG, GPT_10_CHANNEL_TYPE_CONFIG, GPT_10_VALUE_TYPE_CONFIG, GPT_10_MODE_TYPE_CONFIG, GPT_10_TARGET_NUM_TICKS_CONFIG, GPT_10_COUNTER_REPETITION_TYPE_CONFIG,  GPT_10_CLOCK_PRESCALER_CONFIG, GPT_10_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_10_CHANNEL_COUNTING_MODE_CONFIG, GPT_10_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_11_ChannelStatus_CONFIG,GPT_11_ChannelState_CONFIG, GPT_11_CHANNEL_TYPE_CONFIG, GPT_11_VALUE_TYPE_CONFIG, GPT_11_MODE_TYPE_CONFIG, GPT_11_TARGET_NUM_TICKS_CONFIG, GPT_11_COUNTER_REPETITION_TYPE_CONFIG,  GPT_11_CLOCK_PRESCALER_CONFIG, GPT_11_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_11_CHANNEL_COUNTING_MODE_CONFIG, GPT_11_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_12_ChannelStatus_CONFIG,GPT_12_ChannelState_CONFIG, GPT_12_CHANNEL_TYPE_CONFIG, GPT_12_VALUE_TYPE_CONFIG, GPT_12_MODE_TYPE_CONFIG, GPT_12_TARGET_NUM_TICKS_CONFIG, GPT_12_COUNTER_REPETITION_TYPE_CONFIG,  GPT_12_CLOCK_PRESCALER_CONFIG, GPT_12_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_12_CHANNEL_COUNTING_MODE_CONFIG, GPT_12_CHANNEL_COUNTING_DIRECTION_CONFIG,
		GPT_13_ChannelStatus_CONFIG,GPT_13_ChannelState_CONFIG, GPT_13_CHANNEL_TYPE_CONFIG, GPT_13_VALUE_TYPE_CONFIG, GPT_13_MODE_TYPE_CONFIG, GPT_13_TARGET_NUM_TICKS_CONFIG, GPT_13_COUNTER_REPETITION_TYPE_CONFIG,  GPT_13_CLOCK_PRESCALER_CONFIG, GPT_13_CHANNEL_CLOCK_SOURCE_CONFIG, GPT_13_CHANNEL_COUNTING_MODE_CONFIG, GPT_13_CHANNEL_COUNTING_DIRECTION_CONFIG
};
